spring.application.name=phromec-management-spring
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/machinery_parts_erp
spring.datasource.username=root
spring.datasource.password=root
jwt.secret=phromec-management-jwt-secret-key-2026-very-secure
#JWT expires in 1 Hr
jwt.expiration=3600000